/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;
import BaseDatos.BDAlumnos;
import Entidades.Alumnos;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/
public class FrmAlumnos extends javax.swing.JFrame {
    BDAlumnos mBDa=new BDAlumnos();

    /** Creates new form FrmAlumnos */
    public FrmAlumnos() {
        initComponents();
        this.ConsultarAlumnos();
    }

public void ConsultarAlumnos(){
        DefaultTableModel model=new DefaultTableModel();
        this.TableAlumnos.setModel(model);        
        model.addColumn("NC");
        model.addColumn("Nombre");
        model.addColumn("Carrera");
        model.addColumn("Semestre"); 
        model.addColumn("Nivel");    
        ArrayList<Alumnos> ListaAlumnos;
        ListaAlumnos=mBDA.ConsultarAlumnos();
        for (Alumnos alumno : ListaAlumnos) {
               
                model.insertRow(0, new Object[]{producto.getNC(),alumno.getNombre(),producto.getCarrera(), producto.getSemestre, producto.getNivel()});
 }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
         ModificarAlumno();
    }//GEN-LAST:event_BtnModificarActionPerformed

     private void TxtNombreKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             BuscarAlumnos();
        }
    } 
  private void TxtEstatusKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             BuscarAlumnos();
        }
    } 
  private void TxtNivelKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             BuscarAlumnos();
        }
    } 
    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        EliminarAlumno();
        ConsultarAlumnos();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    public void BuscarAlumnos(){
        DefaultTableModel model=new DefaultTableModel();
        this.TableAlumnos.setModel(model);        
        model.addColumn("NC");
        model.addColumn("Nombre");
        model.addColumn("Carrera");
        model.addColumn("Semestre");
        model.addColumn("Nivel");       
        ArrayList<Alumnos> ListaAlumnos;
        Productos malumno=new Alumnos();
        malumno.setNombre(TxtNombre.getText());
        malumno.setEstatus(TxtEstatus.getText());
        malumno.setNivel(TxtNivel.getText());
        ListaAlumnos=mBDA.ConsultarAlumnos(malumno);
        for (alumnos alumno : ListaAlumnos) {
               
                model.insertRow(0, new Object[]{producto.getNC(),alumno.getNombre(),producto.getCarrera(), producto.getSemestre, producto.getNivel()});
        }      
    }
    public void ModificarAlumno(){
        Alumnos malumno= new Alumnos();
        FrmAgregarAlumno mAgregarA= new FrmAgregarAlumno();        
        int fila=TableAlumnos.getSelectedRow();
        malumno.setNC((int) TableAlumnos.getValueAt(fila, 0));        
        malumno.setNombre((String) TableAlumnos.getValueAt(fila, 1));
        malumno.setCarrera((String) TableAlumnos.getValueAt(fila, 2));
        malumno.setSemetre((String) TableAlumnos.getValueAt(fila, 3));
        malumno.setNivel((String) TableAlumnos.getValueAt(fila, 4));
        mAgregarA.HabilitarModificar();
        mAgregarA.AlumnoAnterior(malumno);
        mAgregarA.setVisible(true);        
    }

    public void EliminarProducto(){
        Productos mproducto= new Productos();        
        int fila=TableProductos.getSelectedRow();
        malumno.setNC((int) TableAlumnos.getValueAt(fila, 0));        
        malumno.setNombre((String) TableAlumnos.getValueAt(fila, 1));
        malumno.setCarrera((String) TableAlumnos.getValueAt(fila, 2));
        malumno.setSemetre((String) TableAlumnos.getValueAt(fila, 3));
        malumno.setNivel((String) TableAlumnos.getValueAt(fila, 4));
       
       if( mBDA.EliminarAlumno(malumno))
           JOptionPane.showMessageDialog(null," Alumno Eliminado... ");
       else
           JOptionPane.showMessageDialog(null," No se encontro el Alumno ");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
